### ISSUE TITLE
WC()->session not defined yet

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce-gateway-paypal-express-checkout#459]
Similar to https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/378, I think a user found another case when this happens.

```
2018-07-08T11:43:52+00:00 CRITICAL Uncaught Error: Call to a member function has_session() on null in /home4/theamff0/public_html/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-cart-handler.php:378 
Stack trace: 
#0 /home4/theamff0/public_html/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-cart-handler.php(336): WC_Gateway_PPEC_Cart_Handler->create_nonce('_wc_ppec_start_...') 
#1 /home4/theamff0/public_html/wp-includes/class-wp-hook.php(286): WC_Gateway_PPEC_Cart_Handler->enqueue_scripts('') 
#2 /home4/theamff0/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) 
#3 /home4/theamff0/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) 
#4 /home4/theamff0/public_html/wp-includes/script-loader.php(1447): do_action('wp_enqueue_scri...') 
#5 /home4/theamff0/public_html/wp-includes/class-wp-customize-manager.php(455): wp_enqueue_scripts() 
#6 /home4/theamff0/public_html/wp-includes/class-wp-customize-manager.php(552): W
```

**Comment by bor0** [comment]
I'm closing this one with an assumption that the fix for #464 resolves it. If it re-occurs please re-open.
