### ISSUE TITLE
Call to undefined method WC_Order_Refund::get_order_key()

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce-gateway-paypal-express-checkout#808]
### Describe the bug

Slack thread: p1599652831251300-slack-CJTS771PB
Ticket: 3255765-zd-woothemes

The site received a `[payment_status] => Canceled_Reversal` IPN with a custom arg `{"order_id":87076,"order_key":"***"}`, that 87076 order ID though _may_ (cannot confirm) be associated with a refund because while processing that IPN the follow fatal error occurred. 

```
2020-09-09T07:49:29+00:00 CRITICAL Uncaught Error: Call to undefined method Automattic\WooCommerce\Admin\Overrides\OrderRefund::get_order_key() in /wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/abstracts/abstract-wc-gateway-ppec-paypal-request-handler.php:57
Stack trace:
#0 /wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-ipn-handler.php(95): WC_Gateway_PPEC_PayPal_Request_Handler->get_paypal_order('{"order_id":870...')
#1 /wp-includes/class-wp-hook.php(287): WC_Gateway_PPEC_IPN_Handler->handle_valid_ipn(Array)
#2 /wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#3 /wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-ipn-handler.php(34): do_action('woocommerce_pay in /wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/abstracts/abstract-wc-gateway-ppec-paypal-request-handler.php on line 57
```

If you follow that stacktrace through, you'll find that it is [this line](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/fb334293bbe0e822cf9fbeccd19e737253c1ece0/includes/abstracts/abstract-wc-gateway-ppec-paypal-request-handler.php#L57) that is throwing the error. It just checks that it got something back from `wc_get_order()`, in this case, it did get something back but it was a refund class which doesn't have a `get_order_key()` function. 

I've tried to investigate why a refund ID was passed into the IPN but there's not much history we can find about that ID given you cant search for and view it.

I propose we just tighten that code so it knows we have an order (not a refund) before proceeding.

**Comment by AashikP** [comment]
I'm wondering if this is specifically related to PayPal Checkout. We have a user in 4370972-zen that ran into a similar issue with both PayPal Checkout and PayPal Payments.

We don't have logs for checkout, but refunding an order placed via their account (works fine when our test account is used on their site) returns the following error:

```
Response Body: {"name":"NOT_AUTHORIZED","message":"Authorization failed due to insufficient permissions.","debug_id":"redacted","details":[{"issue":"PERMISSION_DENIED","field":"capture_id","value":"redacted","description":"You do not have permission to access or perform operations on this resource.","location":"path"}],"links":[{"href":"https://developer.paypal.com/docs/api/payments/v2/#error-PERMISSION_DENIED","rel":"information_link"}]}
```

And then if we manually refund the order, we see this error on visiting **Store > My Account page> Orders**

![https://d.pr/i/dVBnXu+](https://d.pr/i/dVBnXu+)

Any thoughts on if this is related?

**Comment by franciscomastromarino** [comment]
Hello guys im seeing this error in my logs:

2025-06-06T01:15:32+00:00 Critical Uncaught Error: Call to undefined method Automattic\WooCommerce\Admin\Overrides\OrderRefund::get_order_key() in /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php:2434  
Additional context
{
    "error": {
        "type": 1,
        "file": "/home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php",
        "line": 2434
    },
    "remote-logging": true,
    "backtrace": [
        "",
        "#0 /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-webhook-handler.php(1357): WC_Stripe_Payment_Gateway->get_order_signature()",
        "#1 /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-webhook-handler.php(993): WC_Stripe_Webhook_Handler->get_order_from_intent()",
        "#2 /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-webhook-handler.php(1318): WC_Stripe_Webhook_Handler->process_payment_intent()",
        "#3 /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-webhook-handler.php(110): WC_Stripe_Webhook_Handler->process_webhook()",
        "#4 /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-includes/class-wp-hook.php(324): WC_Stripe_Webhook_Handler->check_for_webhook()",
        "#5 /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()",
        "#6 /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()",
        "#7 /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-content/plugins/woocommerce/src/Internal/Utilities/LegacyRestApiStub.php(166): do_action()",
        "#8 /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-content/plugins/woocommerce/src/Internal/Utilities/LegacyRestApiStub.php(95): Automattic\WooCommerce\Internal\Utilities\LegacyRestApiStub::maybe_process_wc_api_query_var()",
        "#9 /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Internal\Utilities\LegacyRestApiStub::parse_legacy_rest_api_request()",
        "#10 /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()",
        "#11 /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-includes/plugin.php(565): WP_Hook->do_action()",
        "#12 /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-includes/class-wp.php(418): do_action_ref_array()",
        "#13 /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-includes/class-wp.php(818): WP->parse_request()",
        "#14 /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-includes/functions.php(1342): WP->main()",
        "#15 /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/wp-blog-header.php(16): wp()",
        "#16 /home/1253731.cloudwaysapps.com/gqeuensvmq/public_html/index.php(17): require('...')",
        "#17 {main}",
        "thrown"
    ]
}

is there any fix?
